/**
 * DraftSpec→PDF round-trip behavior: generated bytes load back as a valid
 * document, the CJK font is subset-embedded, and the typeset text (section
 * headings, cover byline, reference lines, disclaimer) extracts back without
 * mojibake through unpdf. Layout inputs (wrapping) are pure-function tested.
 */

import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import fontkit from '@pdf-lib/fontkit'
import { PDFDocument, PDFDict, PDFName } from 'pdf-lib'
import { extractText, getDocumentProxy } from 'unpdf'
import { renderPdf, wrapCjkText, DEFAULT_DISCLAIMER } from '../src/render.ts'
import type { DraftSpec } from '../src/types.ts'

/** A representative multi-section proposal over the 张红喜 scenario. */
function sampleSpec(): DraftSpec {
  return {
    orderNo: 'ORD-20260905-0001',
    title: '中亚货运风险应对方案',
    client: '漯河宏发食品有限公司',
    expert: { name: '张红喜', org: '漯河市电子商务协会（会长）' },
    date: '2026-09-05',
    sections: [
      {
        heading: '背景与问题',
        paragraphs: ['客户食品货量集中于俄罗斯与中亚方向，近期地缘扰动导致主运力与海外仓暴露于不可抗力风险之下。'],
      },
      {
        heading: '风险分析',
        paragraphs: [
          '一级风险：口岸临时关闭与清关延迟，7 日内可恢复；二级风险：单一海外仓停摆或班列线路中断，30 日内可恢复；三级风险：战争损毁、制裁切断支付或主干物流，影响 90 日以上。',
          '',
          '当前客户莫斯科主仓占比过高，一旦受损且无备份仓网络，交期承诺将全面违约。',
        ],
        refs: ['俄罗斯·中亚海外仓风险应对手册（专家知识资产） → 二、应急预案要点'],
      },
      {
        heading: '解决方案',
        paragraphs: [
          '货运：中欧班列为主动线，霍尔果斯与阿拉山口双口岸互备，受阻时切换公路 TIR；仓库：构建「一主两备」网络（莫斯科主仓 + 阿拉木图备仓 + 塔什干备仓），主仓受损 72 小时内启用备仓；合规：EAC 认证与卫生证书提前备案，清关单证四件套标准化。',
        ],
        refs: ['中亚市场准入指南', '2026-08-cim-cmr-force-majeure-excerpt.md'],
      },
    ],
  }
}

describe('renderPdf', () => {
  it('emits loadable PDF bytes with the CJK font embedded and more than one page', async () => {
    const bytes = await renderPdf(sampleSpec())
    expect(bytes.byteLength).toBeGreaterThan(1000)
    expect(Buffer.from(bytes.slice(0, 5)).toString('ascii')).toBe('%PDF-')

    const doc = await PDFDocument.load(bytes)
    expect(doc.getPageCount()).toBeGreaterThan(1)
    // The subset-embedded face keeps its PostScript family name on FontDescriptor keys.
    const baseFonts: string[] = []
    for (const [, obj] of doc.context.enumerateIndirectObjects()) {
      const base = obj instanceof PDFDict ? obj.get(PDFName.of('BaseFont')) : undefined
      if (base !== undefined) baseFonts.push(String(base))
    }
    expect(baseFonts.join(' ')).toContain('NotoSansSC')
  })

  it('typesets cover byline, every section heading, reference lines, and the disclaimer without mojibake', async () => {
    const bytes = await renderPdf(sampleSpec())
    const { text } = await extractedTextOf(bytes)
    for (const expected of [
      '中亚货运风险应对方案',
      '漯河宏发食品有限公司',
      '张红喜',
      '漯河市电子商务协会（会长）',
      'ORD-20260905-0001',
      '背景与问题',
      '风险分析',
      '解决方案',
      '俄罗斯·中亚海外仓风险应对手册（专家知识资产） → 二、应急预案要点',
      '中亚市场准入指南',
      '一主两备',
    ]) {
      expect(text).toContain(expected)
    }
    expect(text).toContain(DEFAULT_DISCLAIMER)
  })

  it('typesets a caller-supplied disclaimer instead of the default one', async () => {
    const bytes = await renderPdf({ ...sampleSpec(), disclaimer: '定制免责声明：以正式合同条款为准。' })
    const { text } = await extractedTextOf(bytes)
    expect(text).toContain('定制免责声明：以正式合同条款为准。')
    expect(text).not.toContain(DEFAULT_DISCLAIMER)
  })

  it('still renders a loadable document for an empty section list', async () => {
    const bytes = await renderPdf({ ...sampleSpec(), sections: [] })
    const doc = await PDFDocument.load(bytes)
    // Cover plus the disclaimer-bearing body page.
    expect(doc.getPageCount()).toBe(2)
  })
})

/** Extract the whole document's text through unpdf (the ToUnicode round-trip witness). */
async function extractedTextOf(bytes: Uint8Array): Promise<{ totalPages: number; text: string }> {
  const pdf = await getDocumentProxy(new Uint8Array(bytes))
  return extractText(pdf, { mergePages: true })
}

/** The bundled Noto Sans SC measured for wrap assertions (Helvetica cannot encode CJK). */
async function notoFont() {
  const doc = await PDFDocument.create()
  doc.registerFontkit(fontkit)
  return doc.embedFont(await readFile(new URL('../resources/fonts/NotoSansSC-Regular.otf', import.meta.url)))
}

describe('wrapCjkText', () => {
  it('breaks a long mixed CJK/latin line within the width budget', async () => {
    const font = await notoFont()
    const line = '客户货量集中于俄罗斯与中亚 direction，需要双口岸互备与 TIR 公路运输预案切换。'.repeat(6)
    const wrapped = wrapCjkText(line, font, 10.5, 445)
    expect(wrapped.length).toBeGreaterThan(1)
    for (const row of wrapped) {
      expect(font.widthOfTextAtSize(row, 10.5)).toBeLessThanOrEqual(445)
    }
    expect(wrapped.join('')).toBe(line)
  })

  it('preserves explicit newlines as hard breaks', async () => {
    const font = await notoFont()
    const wrapped = wrapCjkText('第一段\n第二段', font, 10.5, 445)
    expect(wrapped).toEqual(['第一段', '第二段'])
  })
})
