/**
 * W6-B7: the two JSBlock sources the sourcing batch lays on the 采购管理
 * pages — the bid-comparison matrix (比价表) and the PO status swimlane
 * (采购订单). Pure string exports; the RunJS channel constraints (top-level
 * ctx.render, addEventListener on the live root, no other globals) follow the
 * w6b3/w6b4 block findings. The upgrade markers 'w6b7-matrix' /
 * 'w6b7-po-board' ride inside the code.
 */

/**
 * The comparison-matrix JSBlock: RFQ picker (with status chips), the weight
 * panel (price/lead/quality inputs, sum check, POST /sourcing/config), the
 * grouped three-axis matrix (price heat, rank bars, admission badges, the
 * per-row scoring formula), the award modal (winner confirm + loser
 * disposition), and the award ledger (RFQ→PO back-links). All data comes from
 * the engine's /sourcing/* GETs — the UI never recomputes a score.
 */
export const SOURCING_MATRIX_CODE = [
  "// w6b7-matrix: the upgrade marker (ensureJsBlockOnPage + assert match this)",
  "const ENGINE = String(window.__W6_ENGINE_BASE__ || 'http://127.0.0.1:13110');",
  "const TOKEN = localStorage.getItem('NOCOBASE_TOKEN') || '';",
  "const AMP = '\\u0026';",
  "const esc = (s) => String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': AMP + 'amp;', '<': AMP + 'lt;', '>': AMP + 'gt;', '\"': AMP + 'quot;', \"'\": AMP + '#39;' }[c]));",
  "const state = { rfqs: [], rfq: ((window.location.search || '').match(/[?&]rfq=([^&]+)/) || [])[1] || '', matrix: null, awards: [], note: '', modal: 0 };",
  "const api = async (path, post) => {",
  "  const resp = await fetch(ENGINE + path, post === undefined",
  "    ? { headers: { authorization: 'Bearer ' + TOKEN } }",
  "    : { method: 'POST', headers: { authorization: 'Bearer ' + TOKEN, 'content-type': 'application/json' }, body: JSON.stringify(post) });",
  "  return { status: resp.status, ok: resp.ok, json: await resp.json().catch(() => ({})) };",
  "};",
  "const loadRfqs = async () => {",
  "  const out = await api('/sourcing/rfqs');",
  "  state.rfqs = out.json.rfqs || [];",
  "  if (!state.rfq) { const open = state.rfqs.find(r => r.doc_status !== 'awarded'); state.rfq = (open || state.rfqs[0] || {}).code || ''; }",
  "};",
  "const loadMatrix = async () => {",
  "  state.matrix = null;",
  "  if (!state.rfq) return;",
  "  try {",
  "    const out = await api('/sourcing/matrix?rfq=' + encodeURIComponent(state.rfq));",
  "    if (out.json && out.json.ok) state.matrix = out.json;",
  "    else state.note = '✗ RFQ 不存在或已关闭' + ((out.json && out.json.message) ? '（' + out.json.message + '）' : '（HTTP ' + String(out.status) + '）');",
  "  } catch (e) {",
  "    state.matrix = null;",
  "    state.note = '✗ 比价矩阵加载失败（网络错误：' + String(e && e.message ? e.message : e) + '）';",
  "  }",
  "};",
  "const loadAwards = async () => { state.awards = (await api('/sourcing/awards')).json.awards || []; };",
  "const heat = (min, max, v) => {",
  "  if (!(max > min)) return 'transparent';",
  "  const r = Math.max(0, Math.min(1, (v - min) / (max - min)));",
  "  return r <= 0.5 ? 'rgba(37,111,58,' + (0.10 + 0.22 * (0.5 - r) * 2).toFixed(2) + ')' : 'rgba(170,8,8,' + (0.10 + 0.22 * (r - 0.5) * 2).toFixed(2) + ')';",
  "};",
  "const badge = (kind, text) => kind === 'prevent'",
  "  ? '<span style=\"background:var(--w7-negative-bg);border:1px solid var(--w7-negative-fg);color:var(--w7-negative-fg);border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">prevent ' + esc(text) + '</span>'",
  "  : kind === 'warn' ? '<span style=\"background:var(--w7-critical-bg);border:1px solid var(--w7-critical-fg);color:var(--w7-critical-fg);border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">warn ' + esc(text) + '</span>'",
  "    : '<span style=\"background:var(--w7-positive-bg);border:1px solid var(--w7-positive-fg);color:var(--w7-positive-fg);border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">准入 OK</span>';",
  "const statusColor = (s) => ({ approved: 'var(--w7-positive-fg)', sent: 'var(--w7-informational-fg)', awarded: 'var(--w7-informational-fg)' }[s] || 'var(--w7-neutral-fg)');",
  "const fmt1 = (x) => (x == null ? '—' : String(x));",
  "ctx.render('<div data-w6b7=\"matrix\" style=\"padding:8px\"></div>');",
  "const render = () => {",
  "  const root = document.querySelector('[data-w6b7=\"matrix\"]');",
  "  if (!root) return;",
  "  const m = state.matrix || {};",
  "  const w = m.weights || { price: 50, lead: 30, quality: 20 };",
  "  const rfqOptions = state.rfqs.map(r => '<option value=\"' + esc(r.code) + '\" ' + (r.code === state.rfq ? 'selected' : '') + '>' + esc(r.code) + ' · ' + esc(r.doc_status) + ' · ' + String(r.submitted || 0) + '家报价' + (r.won > 0 ? ' · 已中标' : '') + '</option>').join('');",
  "  let groupsHtml = state.rfqs.length === 0",
  "    ? '<div style=\"color:var(--w7-text-weak);padding:8px 0\">暂无可比价的询价单——仅 approved/sent/awarded 且有已提交报价的询价单会出现在此</div>'",
  "    : '<div style=\"color:var(--w7-text-weak);padding:8px 0\">选择一张询价单查看比价矩阵</div>';",
  "  if (m.ok && m.groups) {",
  "    groupsHtml = m.groups.map(g => {",
  "      const ps = g.rows.map(r => r.unit_price); const ls = g.rows.map(r => r.lead_time_days).filter(v => v != null);",
  "      const rows = g.rows.map(r => {",
  "        const cell = 'padding:5px 8px;border-bottom:1px solid var(--w7-border);font-size:var(--w7-fs-caption);vertical-align:top';",
  "        const bar = '<div style=\"background:var(--w7-surface-2);border-radius:var(--w7-radius-badge);height:14px;width:110px;position:relative\"><div style=\"background:var(--w7-chart-1);border-radius:var(--w7-radius-badge);height:14px;width:' + Math.max(3, Math.round(r.total_score)) + '%\"></div><span style=\"position:absolute;left:60%;top:0;width:1px;height:14px;background:var(--w7-border-strong)\" title=\"60 分合格线\"></span><span style=\"position:absolute;left:6px;top:0;font-size:var(--w7-fs-caption);line-height:14px;color:#fff;font-weight:600\">' + fmt1(r.total_score) + '</span></div>';",
  "        const choose = m.awarded",
  "          ? '<span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">已定标</span>'",
  "          : r.admission === 'prevent'",
  "            ? '<button disabled title=\"' + esc(r.admission_note) + '\" style=\"padding:2px 10px;border:1px solid var(--w7-negative-fg);color:var(--w7-negative-fg);background:var(--w7-negative-bg);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:not-allowed\">禁止定标</button>'",
  "            : '<button data-act=\"choose\" data-q=\"' + String(r.quote_id) + '\" style=\"padding:2px 10px;border:1px solid var(--w7-primary);color:var(--w7-primary);background:var(--w7-surface);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">Choose 定标</button>';",
  "        return '<tr>'",
  "          + '<td style=\"' + cell + ';font-weight:700\">#' + String(r.rank) + '</td>'",
  "          + '<td style=\"' + cell + '\"><b>' + esc(r.supplier_name) + '</b><br>' + badge(r.admission, r.admission_note) + '</td>'",
  "          + '<td style=\"' + cell + ';background:' + heat(Math.min.apply(null, ps), Math.max.apply(null, ps), r.unit_price) + '\">¥' + fmt1(r.unit_price) + ' × ' + fmt1(r.qty) + '<br><b>¥' + fmt1(r.total_price) + '</b></td>'",
  "          + '<td style=\"' + cell + ';background:' + (r.lead_time_days == null ? 'transparent' : heat(Math.min.apply(null, ls), Math.max.apply(null, ls), r.lead_time_days)) + '\">' + (r.lead_time_days == null ? '<i style=\"color:var(--w7-text-weak)\">交期 N/A</i>' : String(r.lead_time_days) + ' 天') + '</td>'",
  "          + '<td style=\"' + cell + '\">' + (r.hist_avg_price == null ? '—' : '¥' + fmt1(r.hist_avg_price)) + '</td>'",
  "          + '<td style=\"' + cell + '\">' + (r.pass_rate == null ? '—' : fmt1(r.pass_rate) + '%') + '</td>'",
  "          + '<td style=\"' + cell + '\"><b>' + (r.quality_score == null ? '—' : fmt1(r.quality_score)) + '</b>' + (r.rating ? ' <span style=\"border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-badge);padding:0 4px;font-size:var(--w7-fs-caption)\">' + esc(r.rating) + '</span>' : '') + '</td>'",
  "          + '<td style=\"' + cell + '\">' + fmt1(r.price_score) + '</td>'",
  "          + '<td style=\"' + cell + '\">' + (r.lead_score == null ? '<i style=\"color:var(--w7-text-weak)\">N/A</i>' : fmt1(r.lead_score)) + '</td>'",
  "          + '<td style=\"' + cell + '\">' + bar + '</td>'",
  "          + '<td style=\"' + cell + '\"><details><summary style=\"cursor:pointer;color:var(--w7-primary)\">算式</summary><div style=\"color:var(--w7-text-secondary);max-width:330px\">' + esc(r.formula) + '</div></details></td>'",
  "          + '<td style=\"' + cell + '\">' + choose + '</td></tr>';",
  "      }).join('');",
  "      return '<div style=\"border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);margin-bottom:10px;overflow:hidden\">'",
  "        + '<div style=\"background:var(--w7-surface-2);padding:6px 10px;font-weight:600\">物料：' + esc(g.product_name) + ' <span style=\"color:var(--w7-text-weak);font-weight:400\">（' + String(g.rows.length) + ' 家报价）</span></div>'",
  "        + '<table style=\"border-collapse:collapse;width:100%\"><thead><tr style=\"background:var(--w7-surface-2);font-size:var(--w7-fs-caption);font-weight:600;color:var(--w7-text-secondary)\">',",
  "        + '<th style=\"padding:4px 8px;text-align:left\">排名</th><th style=\"padding:4px 8px;text-align:left\">供应商</th><th style=\"padding:4px 8px;text-align:left\">报价</th><th style=\"padding:4px 8px;text-align:left\">交期</th><th style=\"padding:4px 8px;text-align:left\">历史成交</th><th style=\"padding:4px 8px;text-align:left\">批次合格率</th><th style=\"padding:4px 8px;text-align:left\">质量分</th><th style=\"padding:4px 8px;text-align:left\">价格分</th><th style=\"padding:4px 8px;text-align:left\">交期分</th><th style=\"padding:4px 8px;text-align:left\">总分</th><th style=\"padding:4px 8px;text-align:left\">计分明细</th><th style=\"padding:4px 8px;text-align:left\">定标</th></tr></thead>'",
  "        + '<tbody>' + rows + '</tbody></table></div>';",
  "    }).join('');",
  "  }",
  "  if (m.ok === false) groupsHtml = '<div style=\"color:var(--w7-negative-fg);padding:8px 0\">' + esc(m.error || '加载失败') + '</div>';",
  "  const awardedBanner = m.awarded",
  "    ? '<div style=\"background:var(--w7-primary-soft);border:1px solid var(--w7-primary);color:var(--w7-primary);border-radius:var(--w7-radius-card);padding:8px 12px;margin-bottom:10px;font-weight:600\">已定标 → ' + esc(m.awarded_po_code || 'PO') + '（中标：' + esc(m.awarded_supplier || '') + '）· 状态 ' + esc(m.rfq_status) + '</div>'",
  "    : '';",
  "  const modalRow = ((state.matrix && state.matrix.groups) || []).reduce((acc, g) => acc.concat(g.rows), []).find(r => r.quote_id === state.modal) || null;",
  "  const modal = state.modal",
  "    ? '<div style=\"position:fixed;inset:0;background:rgba(31,38,48,0.35);z-index:1000;display:flex;align-items:center;justify-content:center\" data-act=\"modal-bg\">'",
  "      + '<div style=\"background:var(--w7-surface);border-radius:var(--w7-radius-card);padding:18px;min-width:340px;box-shadow:var(--w7-shadow-raised)\" data-act=\"modal-card\">'",
  "      + '<div style=\"font-weight:600;margin-bottom:8px\">定标确认 — ' + esc(state.rfq) + '</div>'",
  "      + '<div style=\"font-size:var(--w7-fs-body);color:var(--w7-text-secondary);margin-bottom:10px\"><b>' + esc(modalRow ? modalRow.supplier_name : ('报价行 #' + String(state.modal))) + '</b> 中标'",
  "      + (modalRow ? ' · ¥' + fmt1(modalRow.unit_price) + '×' + fmt1(modalRow.qty) + '=¥' + fmt1(modalRow.total_price) + ' · ' + (modalRow.lead_time_days == null ? '交期 N/A' : '交期 ' + fmt1(modalRow.lead_time_days) + ' 天') + ' · 总分 ' + fmt1(modalRow.total_score) + ' · 排名#' + String(modalRow.rank) : '')",
  "      + '，落选报价处置：</div>'",
  "      + '<label style=\"display:block;font-size:var(--w7-fs-body);margin:4px 0\"><input type=\"radio\" name=\"w6b7-loser\" value=\"cancel\" checked /> 取消落选（status=lost）</label>'",
  "      + '<label style=\"display:block;font-size:var(--w7-fs-body);margin:4px 0\"><input type=\"radio\" name=\"w6b7-loser\" value=\"reserve\" /> 保留后备（status=backup）</label>'",
  "      + '<div style=\"margin-top:12px;text-align:right\">'",
  "      + '<button data-act=\"award\" style=\"padding:4px 16px;border:1px solid var(--w7-primary);color:#fff;background:var(--w7-primary);border-radius:var(--w7-radius-control);margin-right:8px;cursor:pointer\">确认定标</button>'",
  "      + '<button data-act=\"modal-close\" style=\"padding:4px 16px;border:1px solid var(--w7-border-strong);color:var(--w7-text-secondary);background:var(--w7-surface);border-radius:var(--w7-radius-control);cursor:pointer\">取消</button></div>'",
  "      + '<div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak);margin-top:8px\">走引擎 POST /sourcing/award（会话身份推导，采购部/admin 围栏；CAS 幂等）</div></div></div>'",
  "    : '';",
  "  const ledger = state.awards.length === 0",
  "    ? '<div style=\"color:var(--w7-text-weak);padding:6px 0\">（暂无定标记录——PO 回链台账）</div>'",
  "    : '<table style=\"border-collapse:collapse;width:100%;font-size:var(--w7-fs-caption)\"><thead><tr style=\"background:var(--w7-surface-2);font-weight:600;color:var(--w7-text-secondary)\">',",
  "      + '<th style=\"padding:4px 8px;text-align:left\">询价单</th><th style=\"padding:4px 8px;text-align:left\">定标 PO</th><th style=\"padding:4px 8px;text-align:left\">中标供应商</th><th style=\"padding:4px 8px;text-align:left\">金额</th><th style=\"padding:4px 8px;text-align:left\">PO 状态</th><th style=\"padding:4px 8px;text-align:left\">需求日期</th></tr></thead><tbody>'",
  "      + state.awards.map(a => '<tr>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border)\">' + esc(a.rfq_code) + '</td>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border);color:var(--w7-primary)\">' + esc(a.po_code) + '</td>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border)\">' + esc(a.winner) + '</td>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border);font-variant-numeric:tabular-nums\">¥' + esc(a.amount) + '</td>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border)\">' + esc(a.po_status) + '</td>'",
  "        + '<td style=\"padding:4px 8px;border-bottom:1px solid var(--w7-border)\">' + esc(a.need_date || '') + '</td></tr>').join('')",
  "      + '</tbody></table>';",
  "  root.innerHTML = [",
  "    '<div style=\"display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:8px\">',",
  "    '<b>询价单</b>',",
  "    '<select data-w6b7-rfq style=\"padding:4px 8px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control);min-width:260px\">' + rfqOptions + '</select>',",
  "    m.rfq_status ? '<span style=\"color:' + statusColor(m.rfq_status) + ';font-weight:600\">' + esc(m.rfq_status) + '</span>' : '',",
  "    '<span style=\"flex:1\"></span>',",
  "    '<b>权重 价格</b><input data-w6b7-wp type=\"number\" min=\"1\" max=\"98\" value=\"' + String(w.price) + '\" style=\"width:56px;padding:2px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" />',",
  "    '<b>交期</b><input data-w6b7-wl type=\"number\" min=\"1\" max=\"98\" value=\"' + String(w.lead) + '\" style=\"width:56px;padding:2px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" />',",
  "    '<b>质量</b><input data-w6b7-wq type=\"number\" min=\"1\" max=\"98\" value=\"' + String(w.quality) + '\" style=\"width:56px;padding:2px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" />',",
  "    '<button data-act=\"save-weights\" style=\"padding:3px 12px;border:1px solid var(--w7-primary);color:var(--w7-primary);background:var(--w7-surface);border-radius:var(--w7-radius-control);cursor:pointer\">保存权重</button>',",
  "    '<span style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak)\">（POST /sourcing/config → 排名即时重算）</span>',",
  "    '</div>',",
  "    awardedBanner,",
  "    '<div data-w6b7-note style=\"font-size:var(--w7-fs-caption);color:' + (String(state.note).indexOf('✗') === 0 ? 'var(--w7-negative-fg)' : 'var(--w7-positive-fg)') + ';margin-bottom:6px;min-height:16px\">' + esc(state.note) + '</div>',",
  "    groupsHtml,",
  "    '<div style=\"border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:8px 10px;margin-top:12px\"><div style=\"font-weight:700;margin-bottom:6px\">定标台账（RFQ → PO 回链）</div>' + ledger + '</div>',",
  "    modal,",
  "  ].join('');",
  "};",
  "const refresh = async () => { await loadRfqs(); await loadMatrix(); await loadAwards(); render(); };",
  "window.__w6b7Matrix = { state: state, refresh: refresh, setRfq: (code) => { state.rfq = code; } };",
  "setTimeout(async () => {",
  "  const root = document.querySelector('[data-w6b7=\"matrix\"]');",
  "  if (!root) return;",
  "  root.addEventListener('change', (ev) => {",
  "    const t = ev.target;",
  "    if (t && t.getAttribute && t.getAttribute('data-w6b7-rfq') !== null) { state.rfq = t.value; loadMatrix().then(render); }",
  "  });",
  "  root.addEventListener('click', async (ev) => {",
  "    const t = ev.target && ev.target.closest ? ev.target.closest('[data-act]') : null;",
  "    if (!t) return;",
  "    const act = t.getAttribute('data-act');",
  "    if (act === 'choose') { state.modal = Number(t.getAttribute('data-q')); render(); }",
  "    else if (act === 'modal-close' || act === 'modal-bg') { state.modal = 0; render(); }",
  "    else if (act === 'modal-card') { ev.stopPropagation(); }",
  "    else if (act === 'save-weights') {",
  "      const p = Number((root.querySelector('[data-w6b7-wp]') || {}).value);",
  "      const l = Number((root.querySelector('[data-w6b7-wl]') || {}).value);",
  "      const q = Number((root.querySelector('[data-w6b7-wq]') || {}).value);",
  "      const out = await api('/sourcing/config', { weight_price: p, weight_lead: l, weight_quality: q });",
  "      state.note = out.ok ? '权重已保存（' + p + '/' + l + '/' + q + '），排名重算' : '✗ ' + String((out.json || {}).message || (out.json || {}).error || out.status);",
  "      await loadMatrix(); render();",
  "    } else if (act === 'award') {",
  "      const picked = root.querySelector('input[name=\"w6b7-loser\"]:checked');",
  "      const out = await api('/sourcing/award', { rfq_code: state.rfq, winner_quote_id: state.modal, loser_disposition: picked ? picked.value : 'cancel' });",
  "      state.modal = 0;",
  "      if (out.ok) {",
  "        state.note = '已定标 → ' + String(out.json.po_code || '') + (out.json.idempotent ? '（幂等重放' + (out.json.submitted_to ? '，重送审→' + String(out.json.submitted_to) : '') + '）' : '');",
  "      } else {",
  "        const msg = String((out.json || {}).message || (out.json || {}).error || out.status);",
  "        state.note = (out.status === 409 || msg.indexOf('已定标') >= 0) ? '已定标（双击/并发竞态被引擎拒绝）——结果以定标台账为准' : '✗ ' + msg;",
  "      }",
  "      await refresh();",
  "    }",
  "  });",
  "  await refresh();",
  "}, 0);",
].join('\n')

/**
 * The PO swimlane JSBlock: doc_status lanes with per-lane count and amount
 * sum, one card per PO (code, supplier, amount, need-date, the receiving and
 * invoice axis chips, and the sourcing RFQ back-link chip), a code search and
 * a supplier filter on top. Read-only — the engine owns pur_orders.doc_status
 * (no drag surface on purpose).
 */
export const PO_BOARD_CODE = [
  "// w6b7-po-board: the upgrade marker (ensureJsBlockOnPage + assert match this)",
  "const mk = async (name, size) => {",
  "  const r = ctx.makeResource('MultiRecordResource');",
  "  r.setResourceName(name);",
  "  r.setPageSize(size);",
  "  await r.refresh();",
  "  return r.getData() || [];",
  "};",
  "const [pos, rfqs, suppliers] = await Promise.all([mk('pur_orders', 500), mk('pur_rfqs', 200), mk('srm_suppliers', 300)]);",
  "const AMP = '\\u0026';",
  "const esc = (s) => String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': AMP + 'amp;', '<': AMP + 'lt;', '>': AMP + 'gt;', '\"': AMP + 'quot;', \"'\": AMP + '#39;' }[c]));",
  "const rfqCode = {}; for (const r of rfqs) rfqCode[r.id] = r.code;",
  "const supplierName = {}; for (const s of suppliers) supplierName[s.id] = s.name;",
  "const state = { q: '', supplier: 0 };",
  "// W6-R4: the matrix page route (the RFQ back-link chip's href target).",
  "const MATRIX_PAGE = '/admin/w3purb7o0r3yqi45';",
  "const LANES = [",
  "  ['draft', '草稿', 'var(--w7-neutral-fg)'], ['pending', '待审批', 'var(--w7-critical-fg)'], ['pending_level2', '二级审批中', 'var(--w7-informational-fg)'],",
  "  ['approved', '已生效', 'var(--w7-positive-fg)'], ['rejected', '已驳回', 'var(--w7-negative-fg)'], ['void', '已作废', 'var(--w7-neutral-fg)'],",
  "];",
  "const RECEIVING = { none: ['未收货', 'var(--w7-critical-fg)'], partial: ['部分收货', 'var(--w7-informational-fg)'], received: ['收货完成', 'var(--w7-positive-fg)'] };",
  "const INVOICE = { no_invoice: ['未开票', 'var(--w7-critical-fg)'], to_invoice: ['待开票', 'var(--w7-critical-fg)'], invoiced: ['已开票', 'var(--w7-positive-fg)'] };",
  "const chip = (pair) => '<span style=\"border:1px solid ' + pair[1] + ';color:' + pair[1] + ';border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption);white-space:nowrap\">' + esc(pair[0]) + '</span>';",
  "ctx.render('<div data-w6b7=\"po-board\" style=\"padding:8px\"></div>');",
  "const render = () => {",
  "  const root = document.querySelector('[data-w6b7=\"po-board\"]');",
  "  if (!root) return;",
  "  const filtered = pos.filter(o => state.q === '' || String(o.code || '').indexOf(state.q) >= 0)",
  "    .filter(o => state.supplier === 0 || Number(o.supplier_id) === state.supplier);",
  "  const lanes = LANES.map(lane => {",
  "    const cards = filtered.filter(o => String(o.doc_status) === lane[0]);",
  "    const amount = cards.reduce((acc, o) => acc + Number(o.amount || 0), 0);",
  "    const cardHtml = cards.map(o => '<div style=\"background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:8px;margin-bottom:6px;box-shadow:0 1px 2px rgba(0,0,0,0.04)\">'",
  "      + '<div style=\"font-weight:700;margin-bottom:2px\">' + esc(o.code) + '</div>'",
  "      + '<div style=\"font-size:12px;color:var(--w7-text-secondary);margin-bottom:3px\">' + esc(supplierName[o.supplier_id] || ('#' + String(o.supplier_id))) + ' · ¥' + String(Number(o.amount || 0).toLocaleString('zh-CN')) + '</div>'",
  "      + '<div style=\"display:flex;gap:4px;flex-wrap:wrap\">'",
  "      + chip(RECEIVING[o.receiving_status] || [String(o.receiving_status), 'var(--w7-neutral-fg)'])",
  "      + chip(INVOICE[o.invoice_status] || [String(o.invoice_status), 'var(--w7-neutral-fg)'])",
  "      + (o.rfq_id == null ? '' : '<a href=\"' + MATRIX_PAGE + '?rfq=' + encodeURIComponent(rfqCode[o.rfq_id] || ('RFQ#' + String(o.rfq_id))) + '\" title=\"打开比价矩阵\" style=\"background:var(--w7-primary-soft);border:1px solid var(--w7-primary);color:var(--w7-primary);border-radius:4px;padding:0 5px;font-size:11px;white-space:nowrap;text-decoration:none;cursor:pointer\">来自 ' + esc(rfqCode[o.rfq_id] || ('RFQ#' + String(o.rfq_id))) + ' ↗</a>')",
  "      + '</div>'",
  "      + '<div style=\"font-size:11px;color:var(--w7-text-weak);margin-top:3px\">需求日 ' + esc(o.need_date || '—') + '</div>'",
  "      + (o.compare_note ? '<details style=\"margin-top:3px\"><summary style=\"cursor:pointer;color:var(--w7-informational-fg);font-size:var(--w7-fs-caption)\">定标快照（权重/算式/定标人/时间）</summary><div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-secondary);white-space:pre-wrap;border-left:2px solid var(--w7-border-strong);padding-left:6px;margin-top:3px;max-height:150px;overflow:auto\">' + esc(o.compare_note) + '</div></details>' : ''),",
  "      + '</div>').join('');",
  "    return '<div style=\"background:var(--w7-surface-2);border-radius:var(--w7-radius-card);padding:8px;min-width:215px;flex:1\">'",
  "      + '<div style=\"font-weight:600;color:' + lane[2] + ';border-bottom:2px solid ' + lane[2] + ';padding-bottom:4px;margin-bottom:6px\">' + esc(lane[1]) + ' <span style=\"border:1px solid ' + lane[2] + ';color:' + lane[2] + ';border-radius:var(--w7-radius-tag);padding:0 7px;font-size:var(--w7-fs-caption)\">' + String(cards.length) + '</span></div>'",
  "      + '<div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak);margin-bottom:6px\">合计 ¥' + String(amount.toLocaleString('zh-CN')) + '</div>'",
  "      + (cardHtml || '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">（空）</div>') + '</div>';",
  "  }).join('');",
  "  const supplierOptions = '<option value=\"0\">全部供应商</option>' + suppliers.map(s => '<option value=\"' + String(s.id) + '\" ' + (Number(s.id) === state.supplier ? 'selected' : '') + '>' + esc(s.name) + '</option>').join('');",
  "  root.innerHTML = [",
  "    '<div style=\"display:flex;gap:10px;align-items:center;margin-bottom:8px;flex-wrap:wrap\">',",
  "    '<b>采购订单泳道</b><span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">（按审批状态分组 · 只读——状态由审批引擎驱动）</span>',",
  "    '<span style=\"flex:1\"></span>',",
  "    '<input data-w6b7-po-q placeholder=\"搜订单号\" value=\"' + esc(state.q) + '\" style=\"padding:3px 8px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control);width:130px\" />',",
  "    '<select data-w6b7-po-sup style=\"padding:3px 8px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control);max-width:220px\">' + supplierOptions + '</select>',",
  "    '</div>',",
  "    '<div style=\"display:flex;gap:8px;overflow-x:auto;align-items:flex-start\">' + lanes + '</div>',",
  "  ].join('');",
  "};",
  "window.__w6b7PoBoard = { state: state, refresh: render };",
  "setTimeout(() => {",
  "  const root = document.querySelector('[data-w6b7=\"po-board\"]');",
  "  if (!root) return;",
  "  root.addEventListener('change', (ev) => {",
  "    const t = ev.target;",
  "    if (!t || !t.getAttribute) return;",
  "    if (t.getAttribute('data-w6b7-po-q') !== null) { state.q = String(t.value || '').trim(); render(); }",
  "    if (t.getAttribute('data-w6b7-po-sup') !== null) { state.supplier = Number(t.value) || 0; render(); }",
  "  });",
  "  render();",
  "}, 0);",
].join('\n')
