/**
 * W6-B9: the three JSBlock sources the finance-cockpit batch lays on its
 * pages — the 经营总览 cockpit (cards/trend/tops/aging/chain/alerts, the
 * Odoo three-layer dashboard posture), the 财务工作台 (dunning task cards +
 * follow-up timeline + statement generator), and the three-way-match issue
 * workbench (diff-classified rows + open→resolved disposition). Pure string
 * exports; the RunJS channel constraints (top-level ctx.render,
 * addEventListener on the live root, no other globals) follow the w6b7 block
 * findings; multi-line HTML rides [ ... ].join('') arrays (a leading-comma
 * continuation is not legal RunJS syntax — the authoring gate proves it).
 * Upgrade markers 'w6b9-cockpit' / 'w6b9-fin-wb' / 'w6b9-match-wb' ride
 * inside the code. Every number comes from the engine's /fin/* GETs — the
 * UI never recomputes a metric (the cockpit SQL is the one psql
 * reconciles against).
 */

/**
 * The cockpit JSBlock: period filter (30/90/180/365 → engine re-fetch, the
 * Odoo global-filter posture), the five KPI cards (revenue / orders / avg
 * order / overdue AR / due AP — no gross margin by ADR), six secondary chips
 * (received / inventory qty / production hit / OTD / pass rate / open
 * alerts), the monthly revenue trend, the tops (customers view gated to
 * finance/admin server-side), the AR aging bucket bars with click-through
 * customer drill (masked rows say so), the nine-step chain counters, and
 * the open-alert digest.
 */
export const COCKPIT_CODE = [
  "// w6b9-cockpit: the upgrade marker (ensureJsBlockOnPage + assert match this)",
  "const ENGINE = String(window.__W6_ENGINE_BASE__ || 'http://127.0.0.1:13110');",
  "const TOKEN = localStorage.getItem('NOCOBASE_TOKEN') || '';",
  "const AMP = '\\u0026';",
  "const esc = (s) => String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': AMP + 'amp;', '<': AMP + 'lt;', '>': AMP + 'gt;', '\"': AMP + 'quot;', \"'\": AMP + '#39;' }[c]));",
  "const money = (x) => '\\u00a5' + String(Math.round(Number(x || 0)).toLocaleString('zh-CN'));",
  "const KPI_FORMAT = { production_hit: { scale: 100, suffix: '%' }, otd: { scale: 100, suffix: '%' }, pass_rate: { scale: 100, suffix: '%' } };",
  "const formatKpi = (m) => {",
  "  const f = KPI_FORMAT[m.key];",
  "  if (f) return String(Math.round(Number(m.value || 0) * f.scale * 10) / 10) + f.suffix;",
  "  return esc(String(m.value)) + esc(String(m.unit || ''));",
  "};",
  "const state = { days: 90, data: null, agingOpen: '', agingSide: 'ar', note: '', me: '', claiming: 0 };",
  "const api = async (path, post) => {",
  "  const resp = await fetch(ENGINE + path, post === undefined",
  "    ? { headers: { authorization: 'Bearer ' + TOKEN } }",
  "    : { method: 'POST', headers: { authorization: 'Bearer ' + TOKEN, 'content-type': 'application/json' }, body: JSON.stringify(post) });",
  "  return { status: resp.status, ok: resp.ok, json: await resp.json().catch(() => ({})) };",
  "};",
  "const load = async () => {",
  "  state.note = ''; state.data = null;",
  "  try {",
  "    const out = await api('/fin/cockpit?days=' + String(state.days));",
  "    if (out.json && out.json.ok) state.data = out.json;",
  "    else state.note = '\\u2718 \\u9a7e\\u9a76\\u8231\\u52a0\\u8f7d\\u5931\\u8d25\\uff08HTTP ' + String(out.status) + '\\uff1a' + String((out.json && out.json.message) || '') + '\\uff09';",
  "  } catch (e) { state.note = '\\u2718 \\u9a7e\\u9a76\\u8231\\u52a0\\u8f7d\\u5931\\u8d25\\uff08\\u7f51\\u7edc\\u9519\\u8bef\\uff1a' + String(e && e.message ? e.message : e) + '\\uff09'; }",
  "  render();",
  "};",
  "const scrollToPanel = (name) => {",
  "  const el = document.querySelector('[data-panel=\"' + name + '\"]');",
  "  if (el && el.scrollIntoView) el.scrollIntoView({ behavior: 'smooth', block: 'center' });",
  "};",
  "const drillCard = (key) => {",
  "  const d = state.data;",
  "  if (!d) return;",
  "  if (key === 'ar_overdue') {",
  "    state.agingSide = 'ar';",
  "    const first = d.aging.buckets.find((b) => b.customers && b.customers.length > 0) || d.aging.buckets[0];",
  "    if (first) state.agingOpen = first.key;",
  "  } else if (key === 'ap_due') {",
  "    state.agingSide = 'ap';",
  "  }",
  "  render();",
  "  scrollToPanel(key === 'revenue' || key === 'orders' || key === 'avg_order' ? 'trend' : 'aging');",
  "};",
  "const claimAlert = async (id) => {",
  "  if (state.claiming === id) return;",
  "  state.claiming = id;",
  "  render();",
  "  let verdict = '';",
  "  try {",
  "    if (state.me === '') {",
  "      const me = await api('/fin/whoami');",
  "      state.me = String((me.json && me.json.actor) || '');",
  "    }",
  "    const out = await api('/alerts/act', { id: id, action: 'claim', user: state.me });",
  "    verdict = out.json && out.json.ok",
  "      ? '\\u2713 \\u9884\\u8b66 #' + String(id) + ' \\u5df2\\u8ba4\\u9886\\u7ed9 ' + (state.me || '(me)')",
  "      : '\\u2718 \\u8ba4\\u9886\\u88ab\\u62d2\\uff08HTTP ' + String(out.status) + '\\uff1a' + String((out.json && out.json.error) || '') + '\\uff09';",
  "  } catch (e) { verdict = '\\u2718 \\u8ba4\\u9886\\u5931\\u8d25\\uff08' + String(e && e.message ? e.message : e) + '\\uff09'; }",
  "  state.claiming = 0;",
  "  await load();",
  "  state.note = verdict;",
  "  render();",
  "};",
  "const cardHtml = (c) => [",
  "  '<div data-card=\"' + esc(c.key) + '\" style=\"flex:1;min-width:150px;background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:12px 14px;box-shadow:var(--w7-shadow-card);border-top:3px solid ' + (c.critical ? 'var(--w7-negative-fg)' : c.warn ? 'var(--w7-critical-fg)' : 'var(--w7-primary)') + ';cursor:pointer\" title=\"' + esc(c.hint || '') + '\">',",
  "  '<div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak);margin-bottom:4px\">' + esc(c.label) + '</div>',",
  "  '<div style=\"font-size:var(--w7-fs-kpi);font-weight:600;color:' + (c.critical ? 'var(--w7-negative-fg)' : 'var(--w7-text)') + '\">' + (c.unit === '\\u00a5' ? money(c.value) : esc(String(c.value))) + '</div>',",
  "  c.sub ? '<div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak);margin-top:3px\">' + esc(c.sub) + '</div>' : '',",
  "  '</div>'",
  "].join('');",
  "const bar = (label, value, max, color) => [",
  "  '<div style=\"margin-bottom:5px\">',",
  "  '<div style=\"display:flex;justify-content:space-between;font-size:var(--w7-fs-caption);margin-bottom:2px\"><span>' + esc(label) + '</span><b style=\"font-variant-numeric:tabular-nums\">' + esc(String(value)) + '</b></div>',",
  "  '<div style=\"background:var(--w7-surface-2);border-radius:var(--w7-radius-badge);height:10px\">' + (Number(value || 0) <= 0",
  "    ? '<span style=\"display:block;width:3px;height:3px;margin-top:3px;border-radius:999px;background:var(--w7-border-strong)\"></span>'",
  "    : '<div style=\"background:' + color + ';border-radius:var(--w7-radius-badge);height:10px;width:' + String(Math.max(4, Math.round(100 * Number(value || 0) / Math.max(1, Number(max || 1))))) + '%\"></div>') + '</div>',",
  "  '</div>'",
  "].join('');",
  "ctx.render('<div data-w6b9=\"cockpit\" style=\"padding:10px\"></div>');",
  "const render = () => {",
  "  const root = document.querySelector('[data-w6b9=\"cockpit\"]');",
  "  if (!root) return;",
  "  if (!state.data) { root.innerHTML = state.note === '' ? '<div style=\"color:var(--w7-text-weak);padding:10px\">\\u9a7e\\u9a76\\u8231\\u52a0\\u8f7d\\u4e2d\\u2026</div>' : '<div style=\"color:var(--w7-negative-fg);padding:10px\">' + esc(state.note) + '</div>'; return; }",
  "  const d = state.data;",
  "  const periods = [[30, '\\u8fd130\\u5929'], [90, '\\u8fd190\\u5929'], [180, '\\u8fd1180\\u5929'], [365, '\\u8fd11\\u5e74']];",
  "  const headHtml = [",
  "    '<div style=\"display:flex;gap:8px;align-items:center;margin-bottom:10px;flex-wrap:wrap\">',",
  "    '<b style=\"font-size:var(--w7-fs-subtitle)\">\\u7ecf\\u8425\\u603b\\u89c8\\u9a7e\\u9a76\\u8231</b>',",
  "    '<span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\uff08' + esc(d.period.label) + '\\uff09</span>',",
  "    '<span style=\"flex:1\"></span>',",
  "    periods.map(p => '<button data-days=\"' + String(p[0]) + '\" style=\"padding:3px 12px;border:1px solid ' + (state.days === p[0] ? 'var(--w7-primary)' : 'var(--w7-border-strong)') + ';color:' + (state.days === p[0] ? '#fff' : 'var(--w7-text-secondary)') + ';background:' + (state.days === p[0] ? 'var(--w7-primary)' : 'var(--w7-surface)') + ';border-radius:var(--w7-radius-control);cursor:pointer;font-size:var(--w7-fs-caption)\">' + esc(p[1]) + '</button>').join(''),",
  "    '<button data-days=\"reload\" style=\"padding:3px 12px;border:1px solid var(--w7-border-strong);color:var(--w7-text-secondary);background:var(--w7-surface);border-radius:var(--w7-radius-control);cursor:pointer;font-size:var(--w7-fs-caption)\">\\u5237\\u65b0</button>',",
  "    '</div>'",
  "  ].join('');",
  "  const cardsHtml = '<div style=\"display:flex;gap:10px;flex-wrap:wrap;margin-bottom:8px\">' + d.cards.map(cardHtml).join('') + '</div>';",
  "  const miniHtml = '<div style=\"display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px\">' + d.mini.map(m => '<div style=\"background:var(--w7-surface-2);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:6px 10px;font-size:var(--w7-fs-caption)\"><span style=\"color:var(--w7-text-weak)\">' + esc(m.label) + '</span> <b style=\"color:var(--w7-text);font-variant-numeric:tabular-nums\">' + (m.unit === '\\u00a5' ? money(m.value) : formatKpi(m)) + '</b></div>').join('') + '</div>';",
  "  const trendMax = Math.max.apply(null, d.trend.map(t => Number(t.revenue || 0)).concat([1]));",
  "  const trendHtml = d.trend.length === 0 ? '<div style=\"color:var(--w7-text-weak)\">\\u6682\\u65e0\\u8d8b\\u52bf\\u6570\\u636e</div>' : d.trend.map(t => bar(t.ym + ' \\u8425\\u6536 ' + money(t.revenue), t.revenue, trendMax, 'var(--w7-chart-1)')).join('');",
  "  const topHtml = (list, unit) => list.length === 0 ? '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\uff08\\u7a7a\\uff09</div>' : list.map(r => '<div style=\"display:flex;justify-content:space-between;font-size:var(--w7-fs-caption);padding:3px 0;border-bottom:1px dashed var(--w7-border)\"><span>' + esc(r.name) + '</span><b style=\"font-variant-numeric:tabular-nums\">' + (unit === 'money' ? money(r.amount) : esc(String(r.qty)) + ' \\u4ef6') + '</b></div>').join('');",
  "  const agingMax = Math.max.apply(null, d.aging.buckets.map(b => Number(b.amount || 0)).concat([1]));",
  "  const agingColors = ['var(--w7-positive-fg)', 'var(--w7-critical-fg)', 'var(--w7-critical-fg)', 'var(--w7-negative-fg)', 'var(--w7-negative-fg)'];",
  "  const sideBtn = (side, label) => '<button data-side=\"' + side + '\" style=\"padding:2px 10px;border:1px solid ' + (state.agingSide === side ? 'var(--w7-primary)' : 'var(--w7-border-strong)') + ';color:' + (state.agingSide === side ? '#fff' : 'var(--w7-text-secondary)') + ';background:' + (state.agingSide === side ? 'var(--w7-primary)' : 'var(--w7-surface)') + ';border-radius:var(--w7-radius-control);cursor:pointer;font-size:var(--w7-fs-caption)\">' + label + '</button>';",
  "  const apBuckets = (d.aging.ap && d.aging.ap.buckets) || [];",
  "  const apMax = Math.max.apply(null, apBuckets.map(b => Number(b.amount || 0)).concat([1]));",
  "  const agingHtml = [",
  "    '<div style=\"display:flex;gap:6px;align-items:center;margin-bottom:6px\">',",
  "    sideBtn('ar', '\\u5e94\\u6536 AR'), sideBtn('ap', '\\u5e94\\u4ed8 AP'),",
  "    '<span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">' + (state.agingSide === 'ap'",
  "      ? '\\u5230\\u671f\\u5408\\u8ba1 ' + money(d.aging.ap ? d.aging.ap.total : 0)",
  "      : '\\u903e\\u671f\\u5408\\u8ba1 ' + money(d.aging.total)) + '</span>',",
  "    '</div>',",
  "    state.agingSide === 'ap'",
  "      ? (apBuckets.length === 0 ? '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\u6682\\u65e0\\u5230\\u671f\\u672a\\u4ed8\\u53d1\\u7968</div>' : apBuckets.map((b, i) => [",
  "          '<div style=\"margin-bottom:5px\" title=\"\\u5230\\u671f\\u672a\\u4ed8\\u53d1\\u7968\\u6309\\u8d26\\u671f\\u5206\\u6876\">',",
  "          '<div style=\"display:flex;justify-content:space-between;font-size:var(--w7-fs-caption);margin-bottom:2px\"><span>' + esc(b.label) + ' \\uff08' + String(b.count) + ' \\u7968\\uff09</span><b style=\"font-variant-numeric:tabular-nums\">' + money(b.amount) + '</b></div>',",
  "          '<div style=\"background:var(--w7-surface-2);border-radius:var(--w7-radius-badge);height:12px\">' + (Number(b.amount || 0) <= 0 ? '<span style=\"display:block;width:3px;height:3px;margin-top:4px;border-radius:999px;background:var(--w7-border-strong)\"></span>' : '<div style=\"background:' + agingColors[i] + ';border-radius:var(--w7-radius-badge);height:12px;width:' + String(Math.max(4, Math.round(100 * Number(b.amount || 0) / apMax))) + '%\"></div>') + '</div>',",
  "          '</div>'",
  "        ].join('')).join(''))",
  "      : (d.aging.masked",
  "    ? '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\u5ba2\\u6237\\u7ef4\\u5ea6\\u660e\\u7ec6\\u9650 finance/admin \\u67e5\\u770b\\uff08\\u5f53\\u524d\\u89d2\\u8272\\u4ec5\\u89c1\\u5206\\u6876\\u5408\\u8ba1\\uff09</div>'",
  "    : d.aging.buckets.map((b, i) => [",
  "        '<div data-bucket=\"' + esc(b.key) + '\" style=\"margin-bottom:5px;cursor:pointer\" title=\"\\u70b9\\u51fb\\u5c55\\u5f00\\u5ba2\\u6237\\u660e\\u7ec6\">',",
  "        '<div style=\"display:flex;justify-content:space-between;font-size:var(--w7-fs-caption);margin-bottom:2px\"><span>' + esc(b.label) + ' \\uff08' + String(b.count) + ' \\u5355\\uff09</span><b style=\"font-variant-numeric:tabular-nums\">' + money(b.amount) + '</b></div>',",
  "        '<div style=\"background:var(--w7-surface-2);border-radius:var(--w7-radius-badge);height:12px\">' + (Number(b.amount || 0) <= 0 ? '<span style=\"display:block;width:3px;height:3px;margin-top:4px;border-radius:999px;background:var(--w7-border-strong)\"></span>' : '<div style=\"background:' + agingColors[i] + ';border-radius:var(--w7-radius-badge);height:12px;width:' + String(Math.max(4, Math.round(100 * Number(b.amount || 0) / agingMax))) + '%\"></div>') + '</div>',",
  "        state.agingOpen === b.key ? '<div style=\"border:1px solid var(--w7-border);border-radius:var(--w7-radius-control);padding:5px 8px;margin-top:4px\">' + (b.customers.length === 0 ? '<span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\uff08\\u7a7a\\uff09</span>' : b.customers.map(c => '<div style=\"display:flex;justify-content:space-between;font-size:var(--w7-fs-caption);padding:2px 0\"><span>' + esc(c.name) + ' \\uff08' + String(c.count) + ' \\u5355\\uff09</span><b style=\"font-variant-numeric:tabular-nums\">' + money(c.amount) + '</b></div>').join('')) + '</div>' : '',",
  "        '</div>'",
  "      ].join('')).join(''))",
  "  ].join('');",
  "  const chainHtml = d.chain.map(c => [",
  "    '<div style=\"flex:1;min-width:80px;background:' + (c.count > 0 ? 'var(--w7-surface)' : 'var(--w7-surface-2)') + ';border:1px solid ' + (c.hot ? 'var(--w7-negative-fg)' : 'var(--w7-border)') + ';border-radius:var(--w7-radius-card);padding:6px 8px;text-align:center\" title=\"' + esc(c.hint || '') + '\">',",
  "    '<div style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak)\">' + esc(c.label) + '</div>',",
  "    '<div style=\"font-size:var(--w7-fs-subtitle);font-weight:600;color:' + (c.hot ? 'var(--w7-negative-fg)' : 'var(--w7-text)') + '\">' + String(c.count) + '</div>',",
  "    '</div>'",
  "  ].join('')).join('');",
  "  const alertsHtml = d.alerts.length === 0 ? '<div style=\"color:var(--w7-positive-fg);font-size:var(--w7-fs-caption)\">\\u65e0\\u672a\\u5904\\u7406\\u9884\\u8b66</div>' : d.alerts.map(a => [",
  "    '<div style=\"display:flex;gap:6px;font-size:var(--w7-fs-caption);padding:3px 0;border-bottom:1px dashed var(--w7-border);align-items:center\">',",
  "    '<span style=\"background:' + (a.severity === 'critical' ? 'var(--w7-negative-bg)' : 'var(--w7-critical-bg)') + ';color:' + (a.severity === 'critical' ? 'var(--w7-negative-fg)' : 'var(--w7-critical-fg)') + ';border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption);white-space:nowrap\">' + (a.severity === 'critical' ? '\\u7d27\\u6025' : '\\u5173\\u6ce8') + '</span>',",
  "    '<span style=\"color:var(--w7-text-weak);white-space:nowrap\">' + esc(a.rule_label) + '</span><span style=\"flex:1\">' + esc(a.title) + '</span>',",
  "    '<button data-act=\"claim\" data-id=\"' + String(a.id) + '\" style=\"padding:1px 10px;border:1px solid var(--w7-primary);color:' + (state.claiming === a.id ? '#fff' : 'var(--w7-primary)') + ';background:' + (state.claiming === a.id ? 'var(--w7-primary)' : 'var(--w7-surface)') + ';border-radius:var(--w7-radius-control);cursor:pointer;font-size:var(--w7-fs-caption);white-space:nowrap\">' + (state.claiming === a.id ? '\\u8ba4\\u9886\\u4e2d\\u2026' : '\\u8ba4\\u9886') + '</button>',",
  "    '</div>'",
  "  ].join('')).join('');",
  "  const panel = (name, title, body, note) => [",
  "    '<div data-panel=\"' + esc(name) + '\" style=\"background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:10px 12px;box-shadow:var(--w7-shadow-card)\">',",
  "    '<div style=\"font-weight:600;margin-bottom:6px;border-left:3px solid var(--w7-primary);padding-left:8px\">' + esc(title) + (note ? '<span style=\"color:var(--w7-text-weak);font-weight:400;font-size:var(--w7-fs-caption);margin-left:6px\">' + esc(note) + '</span>' : '') + '</div>',",
  "    body, '</div>'",
  "  ].join('');",
  "  root.innerHTML = [headHtml, cardsHtml, miniHtml,",
  "    '<div style=\"display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px\">',",
  "    '<div style=\"flex:2;min-width:300px\">' + panel('trend', '\\u6708\\u5ea6\\u8425\\u6536\\u8d8b\\u52bf\\uff08kpi \\u56de\\u7b97\\u53e3\\u5f84\\uff09', trendHtml) + '</div>',",
  "    '<div style=\"flex:1;min-width:230px\">' + panel('tops-c', 'Top \\u5ba2\\u6237\\uff08\\u671f\\u95f4\\u8425\\u6536\\uff09' + (d.tops.masked ? '\\uff08\\u9650 finance/admin\\uff09' : ''), topHtml(d.tops.customers, 'money')) + '</div>',",
  "    '<div style=\"flex:1;min-width:230px\">' + panel('tops-p', 'Top \\u4ea7\\u54c1\\uff08\\u671f\\u95f4\\u53d1\\u8d27\\u91cf\\uff09', topHtml(d.tops.products, 'qty')) + '</div>',",
  "    '</div>',",
  "    '<div style=\"display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px\">',",
  "    '<div style=\"flex:1;min-width:300px\">' + panel('aging', '\\u8d26\\u9f84\\u5206\\u6876\\uff08AR \\u5e94\\u6536 / AP \\u5e94\\u4ed8\\uff09', agingHtml, state.agingSide === 'ap' ? '\\u5230\\u671f\\u672a\\u4ed8\\u53d1\\u7968\\u6309\\u8d26\\u671f\\u5206\\u6876' : '\\u70b9\\u6876\\u94bb\\u53d6\\u5ba2\\u6237') + '</div>',",
  "    '<div style=\"flex:1;min-width:300px\">' + panel('alerts', '\\u5f02\\u5e38\\u6e05\\u5355\\uff08\\u5f00\\u653e\\u9884\\u8b66\\uff0c\\u8ba4\\u9886\\u8d70 /alerts/act\\uff09', alertsHtml) + '</div>',",
  "    '</div>',",
  "    panel('chain', '\\u8fd0\\u8425\\u94fe\\u8def\\u72b6\\u6001\\uff08\\u4e5d\\u6b65\\u8ba1\\u6570\\uff0c\\u7ea2\\u8fb9=\\u56de\\u6b3e\\u6b65\\uff09', '<div style=\"display:flex;gap:6px;flex-wrap:wrap\">' + chainHtml + '</div>'),",
  "  ].join('');",
  "  if (state.note !== '') {",
  "    const banner = document.querySelector('[data-w6b9=\"cockpit\"] [data-note=\"verdict\"]');",
  "    if (!banner) {",
  "      const div = document.createElement('div');",
  "      div.setAttribute('data-note', 'verdict');",
  "      div.style.cssText = 'padding:6px 10px;margin-bottom:8px;border-radius:var(--w7-radius-control);font-size:var(--w7-fs-body);background:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-bg)' : 'var(--w7-negative-bg)') + ';color:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-fg)' : 'var(--w7-negative-fg)');",
  "      div.textContent = state.note;",
  "      root.insertBefore(div, root.firstChild);",
  "    }",
  "  }",
  "};",
  "window.__w6b9Cockpit = { state: state, refresh: load };",
  "setTimeout(() => {",
  "  const root = document.querySelector('[data-w6b9=\"cockpit\"]');",
  "  if (!root) return;",
  "  root.addEventListener('click', (ev) => {",
  "    const t = ev.target.closest ? ev.target.closest('[data-days],[data-bucket],[data-card],[data-side],[data-act]') : null;",
  "    if (!t) return;",
  "    const act = t.getAttribute('data-act');",
  "    if (act === 'claim') return void claimAlert(Number(t.getAttribute('data-id')));",
  "    const side = t.getAttribute('data-side');",
  "    if (side !== null) { if (state.agingSide !== side) { state.agingSide = side; state.agingOpen = ''; } render(); return; }",
  "    const card = t.getAttribute('data-card');",
  "    if (card !== null) return void drillCard(card);",
  "    const days = t.getAttribute('data-days');",
  "    if (days !== null && days !== 'reload') { state.days = Number(days) || 90; return void load(); }",
  "    if (days === 'reload') return void load();",
  "    const bucket = t.getAttribute('data-bucket');",
  "    if (bucket !== null) { state.agingOpen = state.agingOpen === bucket ? '' : bucket; render(); }",
  "  });",
  "  void load();",
  "}, 0);",
].join('\n')

/**
 * The finance workbench JSBlock: two zones on one page. ① Dunning — the
 * overdue-AR candidates straight from the open ar_overdue alerts (one click
 * creates the task, idempotent per alert), task cards with level/status
 * lights + balance + overdue days + promise date, the follow-up form
 * (kind / note / promise date / result) appending to the append-only
 * timeline, and close with a result. ② Statements — pick a customer and a
 * period, generate (idempotent: same customer+period returns the same
 * statement), and open the printable four-segment page in a new tab.
 */
export const FIN_WORKBENCH_CODE = [
  "// w6b9-fin-wb: the upgrade marker (ensureJsBlockOnPage + assert match this)",
  "const ENGINE = String(window.__W6_ENGINE_BASE__ || 'http://127.0.0.1:13110');",
  "const TOKEN = localStorage.getItem('NOCOBASE_TOKEN') || '';",
  "const AMP = '\\u0026';",
  "const esc = (s) => String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': AMP + 'amp;', '<': AMP + 'lt;', '>': AMP + 'gt;', '\"': AMP + 'quot;', \"'\": AMP + '#39;' }[c]));",
  "const money = (x) => '\\u00a5' + String(Math.round(Number(x || 0)).toLocaleString('zh-CN'));",
  "const state = { candidates: [], tasks: [], statements: [], customers: [], note: '', sel: 0, inFlight: false };",
  "const printUrl = (no) => ENGINE + '/fin/statement/print?statement_no=' + encodeURIComponent(no) + AMP + 'token=' + encodeURIComponent(TOKEN);",
  "const api = async (path, post) => {",
  "  const resp = await fetch(ENGINE + path, post === undefined",
  "    ? { headers: { authorization: 'Bearer ' + TOKEN } }",
  "    : { method: 'POST', headers: { authorization: 'Bearer ' + TOKEN, 'content-type': 'application/json' }, body: JSON.stringify(post) });",
  "  return { status: resp.status, ok: resp.ok, json: await resp.json().catch(() => ({})) };",
  "};",
  "const load = async () => {",
  "  state.note = '';",
  "  try {",
  "    const reads = await Promise.all([api('/fin/dunning/tasks'), api('/fin/dunning/candidates'), api('/fin/statement/list'), api('/fin/customers')]);",
  "    state.tasks = (reads[0].json && reads[0].json.tasks) || [];",
  "    if (reads[0].json && reads[0].json.ok === false) state.note = '\\u2718 ' + String(reads[0].json.message || reads[0].json.error || '');",
  "    state.candidates = (reads[1].json && reads[1].json.candidates) || [];",
  "    state.statements = (reads[2].json && reads[2].json.statements) || [];",
  "    state.customers = (reads[3].json && reads[3].json.customers) || [];",
  "  } catch (e) { state.note = '\\u2718 \\u8d22\\u52a1\\u5de5\\u4f5c\\u53f0\\u52a0\\u8f7d\\u5931\\u8d25\\uff08' + String(e && e.message ? e.message : e) + '\\uff09'; }",
  "  render();",
  "};",
  "const act = async (path, body, verb) => {",
  "  if (state.inFlight) return;",
  "  state.inFlight = true;",
  "  try {",
  "    const out = await api(path, body);",
  "    if (out.json && out.json.ok && out.json.statement_no) {",
  "      window.open(printUrl(out.json.statement_no), '_blank');",
  "    }",
  "    await load();",
  "    state.note = out.json && out.json.ok",
  "      ? '\\u2713 ' + verb + '\\u6210\\u529f' + (out.json.duplicate ? '\\uff08\\u5df2\\u5b58\\u5728\\uff0c\\u8fd4\\u56de\\u540c\\u4e00\\u4efd\\uff09' : '')",
  "      : '\\u2718 ' + verb + '\\u88ab\\u62d2\\uff08HTTP ' + String(out.status) + '\\uff1a' + String((out.json && (out.json.message || out.json.error)) || '') + '\\uff09';",
  "  } catch (e) {",
  "    state.note = '\\u2718 ' + verb + '\\u5931\\u8d25\\uff08' + String(e && e.message ? e.message : e) + '\\uff09';",
  "  } finally {",
  "    state.inFlight = false;",
  "  }",
  "  render();",
  "};",
  "const STATUS = { open: ['\\u5f85\\u8ddf\\u8fdb', 'var(--w7-critical-fg)', 'var(--w7-critical-bg)'], contacted: ['\\u5df2\\u8054\\u7cfb', 'var(--w7-informational-fg)', 'var(--w7-informational-bg)'], promised: ['\\u5df2\\u627f\\u8bfa', 'var(--w7-informational-fg)', 'var(--w7-informational-bg)'], closed: ['\\u5df2\\u5173\\u95ed', 'var(--w7-positive-fg)', 'var(--w7-positive-bg)'], bad_debt: ['\\u574f\\u8d26', 'var(--w7-negative-fg)', 'var(--w7-negative-bg)'] };",
  "const KINDS = { phone: '\\u7535\\u8bdd', visit: '\\u4e0a\\u95e8', email: '\\u90ae\\u4ef6', note: '\\u5907\\u6ce8' };",
  "const RESULTS = { reached: '\\u63a5\\u901a\\uff08\\u5f53\\u573a\\u672a\\u4ed8\\uff09', no_answer: '\\u672a\\u63a5\\u901a', promised: '\\u627f\\u8bfa\\u4ed8\\u6b3e', partial_paid: '\\u90e8\\u5206\\u56de\\u6b3e', refused: '\\u62d2\\u4ed8' };",
  "const cell = 'padding:5px 8px;border-bottom:1px solid var(--w7-border);font-size:var(--w7-fs-caption);vertical-align:top';",
  "const th = cell + ';text-align:left;font-weight:600';",
  "ctx.render('<div data-w6b9=\"fin-wb\" style=\"padding:10px\"></div>');",
  "function render() {",
  "  const root = document.querySelector('[data-w6b9=\"fin-wb\"]');",
  "  if (!root) return;",
  "  const noteHtml = state.note === '' ? '' : '<div style=\"padding:6px 10px;margin-bottom:8px;border-radius:var(--w7-radius-control);font-size:var(--w7-fs-body);background:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-bg)' : 'var(--w7-negative-bg)') + ';color:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-fg)' : 'var(--w7-negative-fg)') + '\">' + esc(state.note) + '</div>';",
  "  const candHtml = state.candidates.length === 0",
  "    ? '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\u65e0\\u5f85\\u50ac\\u6536\\u7684\\u8d26\\u671f\\u9884\\u8b66\\uff08ar_overdue \\u5f00\\u653e\\u884c\\u5747\\u5df2\\u5efa\\u4efb\\u52a1\\uff09</div>'",
  "    : state.candidates.map(c => [",
  "        '<div style=\"display:flex;gap:8px;align-items:center;padding:5px 8px;border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);margin-bottom:5px;background:var(--w7-critical-bg);font-size:var(--w7-fs-caption)\">',",
  "        '<span style=\"background:' + (c.severity === 'critical' ? 'var(--w7-negative-bg)' : 'var(--w7-critical-bg)') + ';color:' + (c.severity === 'critical' ? 'var(--w7-negative-fg)' : 'var(--w7-critical-fg)') + ';border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">' + (c.severity === 'critical' ? '\\u7d27\\u6025' : '\\u5173\\u6ce8') + '</span>',",
  "        '<span style=\"flex:1\">' + esc(c.title) + '\\uff08\\u9884\\u8b66 #' + String(c.id) + '\\uff09</span>',",
  "        '<button data-act=\"create\" data-id=\"' + String(c.id) + '\" style=\"padding:2px 12px;border:1px solid var(--w7-primary);color:var(--w7-primary);background:var(--w7-surface);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">\\u5efa\\u50ac\\u6536\\u4efb\\u52a1</button>',",
  "        '</div>'",
  "      ].join('')).join('');",
  "  const taskHtml = state.tasks.length === 0",
  "    ? '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\u6682\\u65e0\\u50ac\\u6536\\u4efb\\u52a1</div>'",
  "    : state.tasks.map(t => {",
  "      const st = STATUS[t.status] || [t.status, 'var(--w7-neutral-fg)', 'var(--w7-neutral-bg)'];",
  "      const records = (t.records || []).map(r => [",
  "        '<div style=\"font-size:var(--w7-fs-caption);padding:3px 0;border-bottom:1px dashed var(--w7-border)\">',",
  "        '<b>[' + esc(KINDS[r.kind] || r.kind) + ']</b> ' + esc(r.note),",
  "        r.promise_date ? ' \\uff08\\u627f\\u8bfa ' + esc(r.promise_date) + '\\uff09' : '',",
  "        ' \\u2192 ' + esc(RESULTS[r.result] || r.result),",
  "        ' <span style=\"color:var(--w7-text-weak)\">' + esc(r.actor) + ' @ ' + esc(String(r.ts || '').slice(0, 16).replace('T', ' ')) + '</span></div>'",
  "      ].join('')).join('');",
  "      const open = state.sel === Number(t.id);",
  "      return [",
  "        '<div style=\"border:1px solid ' + (open ? 'var(--w7-primary)' : 'var(--w7-border)') + ';border-radius:var(--w7-radius-card);margin-bottom:8px;background:var(--w7-surface);overflow:hidden\">',",
  "        '<div data-act=\"sel\" data-id=\"' + String(t.id) + '\" style=\"display:flex;gap:8px;align-items:center;padding:8px 10px;cursor:pointer;flex-wrap:wrap\">',",
  "        '<b>' + esc(t.task_no) + '</b>',",
  "        '<span style=\"background:' + st[2] + ';color:' + st[1] + ';border-radius:var(--w7-radius-badge);padding:0 6px;font-size:var(--w7-fs-caption)\">\\u25cf ' + esc(st[0]) + '</span>',",
  "        '<span style=\"border:1px solid var(--w7-border-strong);color:var(--w7-text-secondary);border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">' + esc(t.level) + '</span>',",
  "        '<span style=\"flex:1;font-size:var(--w7-fs-body)\">' + esc(t.customer_name) + ' \\u00b7 ' + esc(t.so_code) + '</span>',",
  "        '<b style=\"color:var(--w7-negative-fg);font-variant-numeric:tabular-nums\">' + money(t.balance) + '</b>',",
  "        '<span style=\"font-size:var(--w7-fs-caption);color:var(--w7-text-weak)\">\\u903e\\u671f ' + String(t.days_overdue) + ' \\u5929</span>',",
  "        t.promise_date ? '<span style=\"font-size:var(--w7-fs-caption);color:var(--w7-informational-fg)\">\\u627f\\u8bfa ' + esc(t.promise_date) + '</span>' : '',",
  "        t.owner ? '<span style=\"font-size:var(--w7-fs-caption);color:var(--w7-primary)\">\\u8d23\\u4efb\\u4eba ' + esc(t.owner) + '</span>' : '',",
  "        '</div>',",
  "        open ? [",
  "          '<div style=\"border-top:1px solid var(--w7-border);padding:8px 10px\">',",
  "          '<div style=\"max-height:180px;overflow:auto;margin-bottom:8px\">' + (records || '<div style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\u6682\\u65e0\\u8ddf\\u8fdb\\u8bb0\\u5f55</div>') + '</div>',",
  "          (t.status === 'closed' || t.status === 'bad_debt')",
  "            ? '<div style=\"color:var(--w7-positive-fg);font-size:var(--w7-fs-caption)\">\\u5df2\\u5173\\u95ed\\uff08' + esc(t.close_result || '') + '\\uff09\\u2014\\u2014\\u8bb0\\u5f55\\u4ec5\\u5c55\\u793a\\uff08append-only\\uff09</div>'",
  "            : [",
  "              '<div style=\"display:flex;gap:6px;flex-wrap:wrap;align-items:center;font-size:var(--w7-fs-caption)\">',",
  "              '<select data-in=\"kind\">' + Object.keys(KINDS).map(k => '<option value=\"' + k + '\">' + KINDS[k] + '</option>').join('') + '</select>',",
  "              '<input data-in=\"note\" placeholder=\"\\u8ddf\\u8fdb\\u8bb0\\u5f55\\uff08\\u5fc5\\u586b\\uff09\" style=\"flex:1;min-width:160px;padding:3px 8px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" />',",
  "              '<input data-in=\"promise\" type=\"date\" title=\"\\u627f\\u8bfa\\u4ed8\\u6b3e\\u65e5\\uff08\\u53ef\\u9009\\uff09\" style=\"padding:3px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" />',",
  "              '<select data-in=\"result\">' + Object.keys(RESULTS).map(k => '<option value=\"' + k + '\">' + RESULTS[k] + '</option>').join('') + '</select>',",
  "              '<button data-act=\"followup\" data-id=\"' + String(t.id) + '\" style=\"padding:3px 14px;border:1px solid var(--w7-primary);color:#fff;background:var(--w7-primary);border-radius:var(--w7-radius-control);cursor:pointer\">\\u8bb0\\u5f55\\u8ddf\\u8fdb</button>',",
  "              '<button data-act=\"close\" data-id=\"' + String(t.id) + '\" style=\"padding:3px 14px;border:1px solid var(--w7-positive-fg);color:var(--w7-positive-fg);background:var(--w7-surface);border-radius:var(--w7-radius-control);cursor:pointer\" title=\"\\u5173\\u95ed\\u524d\\u9700\\u81f3\\u5c11\\u4e00\\u6761\\u8ddf\\u8fdb\\u8bb0\\u5f55\">\\u5173\\u95ed\\u4efb\\u52a1</button>',",
  "              '</div>'",
  "            ].join(''),",
  "          '</div>',",
  "        ].join('') : '',",
  "        '</div>'",
  "      ].join('');",
  "    }).join('');",
  "  const stmtRows = state.statements.length === 0",
  "    ? '<tr><td colspan=\"5\" style=\"' + cell + '\">\\u6682\\u65e0\\u5df2\\u751f\\u6210\\u5bf9\\u8d26\\u5355</td></tr>'",
  "    : state.statements.map(s => [",
  "        '<tr>',",
  "        '<td style=\"' + cell + '\">' + esc(s.statement_no) + '</td>',",
  "        '<td style=\"' + cell + '\">' + esc(s.customer_name) + '</td>',",
  "        '<td style=\"' + cell + '\">' + esc(s.period_start) + ' ~ ' + esc(s.period_end) + '</td>',",
  "        '<td style=\"' + cell + ';text-align:right\">' + money(s.closing_amount) + '</td>',",
  "        '<td style=\"' + cell + '\"><a href=\"' + printUrl(s.statement_no) + '\" target=\"_blank\" style=\"color:var(--w7-primary)\">\\u6253\\u5370/\\u5bfc\\u51fa PDF \\u2197</a></td>',",
  "        '</tr>'",
  "      ].join('')).join('');",
  "  const custOptions = state.customers.map(c => '<option value=\"' + String(c.id) + '\">' + esc(c.name) + '</option>').join('');",
  "  const today = new Date();",
  "  const iso = (d) => d.toISOString().slice(0, 10);",
  "  const quarterStart = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3, 1);",
  "  root.innerHTML = [",
  "    noteHtml,",
  "    '<div style=\"background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:10px 12px;margin-bottom:10px;box-shadow:var(--w7-shadow-card)\">',",
  "    '<div style=\"font-weight:600;margin-bottom:6px;border-left:3px solid var(--w7-negative-fg);padding-left:8px\">\\u50ac\\u6536\\u5f85\\u529e\\uff08\\u8d26\\u671f\\u9884\\u8b66 \\u2192 \\u50ac\\u6536\\u4efb\\u52a1\\uff09</div>',",
  "    candHtml, '</div>',",
  "    '<div style=\"background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:10px 12px;margin-bottom:10px;box-shadow:var(--w7-shadow-card)\">',",
  "    '<div style=\"font-weight:600;margin-bottom:6px;border-left:3px solid var(--w7-critical-fg);padding-left:8px\">\\u50ac\\u6536\\u4efb\\u52a1\\uff08\\u72b6\\u6001\\u706f + \\u8ddf\\u8fdb\\u65f6\\u95f4\\u7ebf\\uff0c\\u8bb0\\u5f55 append-only\\uff09</div>',",
  "    taskHtml, '</div>',",
  "    '<div style=\"background:var(--w7-surface);border:1px solid var(--w7-border);border-radius:var(--w7-radius-card);padding:10px 12px;box-shadow:var(--w7-shadow-card)\">',",
  "    '<div style=\"font-weight:600;margin-bottom:6px;border-left:3px solid var(--w7-positive-fg);padding-left:8px\">\\u5ba2\\u6237\\u5bf9\\u8d26\\u5355\\uff08\\u56db\\u6bb5\\u5f0f\\uff1a\\u671f\\u521d + \\u53d1\\u8d27 \\u2212 \\u56de\\u6b3e = \\u671f\\u672b\\uff09</div>',",
  "    '<div style=\"display:flex;gap:6px;flex-wrap:wrap;align-items:center;font-size:var(--w7-fs-caption);margin-bottom:8px\">',",
  "    '<select data-in=\"stcust\">' + custOptions + '</select>',",
  "    '<label>\\u671f\\u95f4 <input data-in=\"ststart\" type=\"date\" value=\"' + iso(quarterStart) + '\" style=\"padding:3px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" /></label>',",
  "    '<label>\\u2190\\u2192 <input data-in=\"stend\" type=\"date\" value=\"' + iso(today) + '\" style=\"padding:3px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control)\" /></label>',",
  "    '<button data-act=\"genstmt\" style=\"padding:3px 14px;border:1px solid var(--w7-primary);color:#fff;background:var(--w7-primary);border-radius:var(--w7-radius-control);cursor:pointer\">\\u751f\\u6210\\u5bf9\\u8d26\\u5355\\uff08\\u5e42\\u7b49\\uff1a\\u540c\\u5ba2\\u6237\\u540c\\u671f\\u95f4\\u8fd4\\u56de\\u540c\\u4e00\\u4efd\\uff09</button>',",
  "    '</div>',",
  "    '<table style=\"border-collapse:collapse;width:100%\"><thead><tr style=\"background:var(--w7-surface-2);font-size:var(--w7-fs-caption);font-weight:600;color:var(--w7-text-secondary)\">',",
  "    '<th style=\"' + th + '\">\\u5355\\u53f7</th><th style=\"' + th + '\">\\u5ba2\\u6237</th><th style=\"' + th + '\">\\u671f\\u95f4</th><th style=\"' + th + '\">\\u671f\\u672b\\u4f59\\u989d</th><th style=\"' + th + '\">\\u64cd\\u4f5c</th></tr></thead><tbody>' + stmtRows + '</tbody></table>',",
  "    '</div>',",
  "  ].join('');",
  "}",
  "window.__w6b9FinWb = { state: state, refresh: load };",
  "setTimeout(() => {",
  "  const root = document.querySelector('[data-w6b9=\"fin-wb\"]');",
  "  if (!root) return;",
  "  root.addEventListener('click', (ev) => {",
  "    const t = ev.target.closest ? ev.target.closest('[data-act]') : null;",
  "    if (!t) return;",
  "    const id = Number(t.getAttribute('data-id'));",
  "    const what = t.getAttribute('data-act');",
  "    if (what === 'sel') { state.sel = state.sel === id ? 0 : id; render(); return; }",
  "    if (what === 'create') return void act('/fin/dunning/create', { alert_id: id }, '\\u5efa\\u4efb\\u52a1');",
  "    if (what === 'followup') {",
  "      const noteEl = root.querySelector('[data-in=\"note\"]');",
  "      const note = noteEl ? String(noteEl.value || '').trim() : '';",
  "      if (note === '') { state.note = '\\u2718 \\u8ddf\\u8fdb\\u8bb0\\u5f55\\u5fc5\\u586b\\u4e0d\\u80fd\\u4e3a\\u7a7a'; render(); return; }",
  "      const kind = String(((root.querySelector('[data-in=\"kind\"]') || {}).value) || 'phone');",
  "      const promise = String(((root.querySelector('[data-in=\"promise\"]') || {}).value) || '');",
  "      const result = String(((root.querySelector('[data-in=\"result\"]') || {}).value) || 'reached');",
  "      const msgId = 'fu-' + String(id) + '-' + String(Date.now()) + '-' + String(Math.random()).slice(2, 8);",
  "      return void act('/fin/dunning/followup', { task_id: id, kind: kind, note: note, promise_date: promise === '' ? undefined : promise, result: result, client_msg_id: msgId }, '\\u8bb0\\u5f55\\u8ddf\\u8fdb');",
  "    }",
  "    if (what === 'close') return void act('/fin/dunning/close', { task_id: id, close_result: 'paid' }, '\\u5173\\u95ed\\u4efb\\u52a1');",
  "    if (what === 'genstmt') {",
  "      const custSel = root.querySelector('[data-in=\"stcust\"]');",
  "      const startEl = root.querySelector('[data-in=\"ststart\"]');",
  "      const endEl = root.querySelector('[data-in=\"stend\"]');",
  "      const custId = custSel ? Number(custSel.value || 0) : 0;",
  "      const start = startEl ? String(startEl.value || '') : '';",
  "      const end = endEl ? String(endEl.value || '') : '';",
  "      if (!custId || start === '' || end === '' || start > end) { state.note = '\\u2718 \\u9700\\u9009\\u5ba2\\u6237\\u4e14\\u671f\\u95f4\\u8d77\\u2192\\u6b62\\u5408\\u6cd5'; render(); return; }",
  "      return void act('/fin/statement/generate', { customer_id: custId, period_start: start, period_end: end }, '\\u751f\\u6210\\u5bf9\\u8d26\\u5355');",
  "    }",
  "  });",
  "  void load();",
  "}, 0);",
].join('\n')

/**
 * The three-way-match issue workbench JSBlock: the diff rows the engine's
 * PO-receipt-invoice reconciliation produced (qty_short / price_diff /
 * no_receipt), grouped counts by class, and the disposition actions
 * (resolved / waived with a note) that walk the open→resolved|waived state
 * machine — the receipt-then-pay gate mirrors Odoo's "Should Be Paid" flag.
 */
export const MATCH_WB_CODE = [
  "// w6b9-match-wb: the upgrade marker (ensureJsBlockOnPage + assert match this)",
  "const ENGINE = String(window.__W6_ENGINE_BASE__ || 'http://127.0.0.1:13110');",
  "const TOKEN = localStorage.getItem('NOCOBASE_TOKEN') || '';",
  "const AMP = '\\u0026';",
  "const esc = (s) => String(s == null ? '' : s).replace(/[&<>\"']/g, (c) => ({ '&': AMP + 'amp;', '<': AMP + 'lt;', '>': AMP + 'gt;', '\"': AMP + 'quot;', \"'\": AMP + '#39;' }[c]));",
  "const money = (x) => '\\u00a5' + String(Math.round(Number(x || 0) * 100) / 100);",
  "const state = { issues: [], filter: '', note: '', resolveSel: 0, resolveKind: '', resolveDraft: '', inFlight: false };",
  "const api = async (path, post) => {",
  "  const resp = await fetch(ENGINE + path, post === undefined",
  "    ? { headers: { authorization: 'Bearer ' + TOKEN } }",
  "    : { method: 'POST', headers: { authorization: 'Bearer ' + TOKEN, 'content-type': 'application/json' }, body: JSON.stringify(post) });",
  "  return { status: resp.status, ok: resp.ok, json: await resp.json().catch(() => ({})) };",
  "};",
  "const load = async () => {",
  "  state.note = '';",
  "  try {",
  "    const out = await api('/fin/match/issues');",
  "    state.issues = (out.json && out.json.issues) || [];",
  "    if (out.json && out.json.ok === false) state.note = '\\u2718 ' + String(out.json.message || out.json.error || '');",
  "  } catch (e) { state.note = '\\u2718 \\u4e09\\u5355\\u5dee\\u5f02\\u52a0\\u8f7d\\u5931\\u8d25\\uff08' + String(e && e.message ? e.message : e) + '\\uff09'; }",
  "  render();",
  "};",
  "const TYPES = {",
  "  qty_short: ['\\u6570\\u91cf\\u5dee\\uff08\\u5df2\\u5f00\\u7968 > \\u5df2\\u6536\\u8d27\\uff09', 'var(--w7-critical-fg)', 'var(--w7-critical-bg)'],",
  "  price_diff: ['\\u4ef7\\u683c\\u5dee\\uff08\\u8d85\\u5bb9\\u5dee\\uff09', 'var(--w7-negative-fg)', 'var(--w7-negative-bg)'],",
  "  no_receipt: ['\\u7f3a\\u5931\\u6536\\u8d27\\u5355', 'var(--w7-negative-fg)', 'var(--w7-negative-bg)'],",
  "};",
  "const ST = { open: ['\\u5f85\\u5904\\u7f6e', 'var(--w7-informational-fg)'], resolved: ['\\u5df2\\u5904\\u7f6e', 'var(--w7-positive-fg)'], waived: ['\\u5df2\\u8c41\\u514d\\u653e\\u884c', 'var(--w7-neutral-fg)'] };",
  "ctx.render('<div data-w6b9=\"match-wb\" style=\"padding:8px\"></div>');",
  "function render() {",
  "  const root = document.querySelector('[data-w6b9=\"match-wb\"]');",
  "  if (!root) return;",
  "  const cell = 'padding:5px 8px;border-bottom:1px solid var(--w7-border);font-size:var(--w7-fs-caption);vertical-align:top';",
  "  const counts = {}; for (const i of state.issues) if (i.status === 'open') counts[i.diff_type] = (counts[i.diff_type] || 0) + 1;",
  "  const chips = ['', ...Object.keys(TYPES)].map(k => [",
  "    '<button data-filter=\"' + k + '\" style=\"margin-right:6px;padding:2px 10px;border:1px solid ' + (state.filter === k ? 'var(--w7-primary)' : 'var(--w7-border-strong)') + ';color:' + (state.filter === k ? '#fff' : 'var(--w7-text-secondary)') + ';background:' + (state.filter === k ? 'var(--w7-primary)' : 'var(--w7-surface)') + ';border-radius:var(--w7-radius-control);cursor:pointer;font-size:var(--w7-fs-caption)\">',",
  "    k === '' ? '\\u5168\\u90e8\\uff08' + String(state.issues.filter(i => i.status === 'open').length) + ' \\u5f85\\u5904\\u7f6e\\uff09' : esc(TYPES[k][0]) + ' \\u00d7 ' + String(counts[k] || 0),",
  "    '</button>'",
  "  ].join('')).join('');",
  "  const rows = state.issues",
  "    .filter(i => state.filter === '' || i.diff_type === state.filter)",
  "    .map(i => {",
  "      const st = ST[i.status] || [i.status, 'var(--w7-neutral-fg)'];",
  "      const ty = TYPES[i.diff_type] || [i.diff_type, 'var(--w7-neutral-fg)', 'var(--w7-neutral-bg)'];",
  "      const resolving = i.status === 'open' && state.resolveSel === Number(i.id);",
  "      return [",
  "        '<tr>',",
  "        '<td style=\"' + cell + '\"><b>' + esc(i.invoice_no) + '</b><br><span style=\"color:var(--w7-text-weak)\">PO ' + esc(i.po_code) + '</span></td>',",
  "        '<td style=\"' + cell + '\"><span style=\"background:' + ty[2] + ';color:' + ty[1] + ';border-radius:var(--w7-radius-badge);padding:0 5px;font-size:var(--w7-fs-caption)\">' + esc(ty[0]) + '</span></td>',",
  "        '<td style=\"' + cell + '\">' + esc(i.detail) + '</td>',",
  "        '<td style=\"' + cell + '\"><span style=\"color:' + st[1] + '\">\\u25cf ' + esc(st[0]) + '</span>',",
  "          i.status !== 'open' ? '<br><span style=\"color:var(--w7-text-weak)\">' + esc(i.resolved_by || '') + ' @ ' + esc(String(i.resolved_at || '').slice(0, 10)) + '<br>' + esc(i.resolve_note || '') + '</span>' : '',",
  "        '</td>',",
  "        '<td style=\"' + cell + '\">' + (i.status === 'open'",
  "          ? (resolving",
  "            ? [",
  "                '<div style=\"margin-bottom:4px;color:var(--w7-text-weak)\">\\u5904\\u7f6e\\u8bf4\\u660e\\uff08' + (state.resolveKind === 'waived' ? '\\u8c41\\u514d\\u653e\\u884c' : '\\u5904\\u7f6e\\u5b8c\\u6bd5') + '\\uff0c\\u843d\\u8868\\u7559\\u75d5\\uff09</div>',",
  "                '<textarea data-in=\"resolve-note\" rows=\"2\" style=\"width:95%;padding:4px 6px;border:1px solid var(--w7-border-strong);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);box-sizing:border-box\">' + esc(state.resolveDraft) + '</textarea>',",
  "                '<div style=\"margin-top:4px\">',",
  "                '<button data-act=\"resolve-confirm\" data-id=\"' + String(i.id) + '\" data-kind=\"' + esc(state.resolveKind) + '\" style=\"padding:2px 10px;border:1px solid var(--w7-primary);color:#fff;background:var(--w7-primary);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">\\u786e\\u8ba4\\u63d0\\u4ea4</button>',",
  "                '<button data-act=\"resolve-cancel\" style=\"padding:2px 10px;margin-left:4px;border:1px solid var(--w7-border-strong);color:var(--w7-text-secondary);background:var(--w7-surface);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">\\u53d6\\u6d88</button>',",
  "                '</div>',",
  "              ].join('')",
  "            : [",
  "                '<button data-act=\"resolve\" data-id=\"' + String(i.id) + '\" data-kind=\"resolved\" style=\"padding:2px 8px;border:1px solid var(--w7-positive-fg);color:var(--w7-positive-fg);background:var(--w7-surface);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">\\u5904\\u7f6e\\u5b8c\\u6bd5</button>',",
  "                '<button data-act=\"resolve\" data-id=\"' + String(i.id) + '\" data-kind=\"waived\" style=\"padding:2px 8px;border:1px solid var(--w7-neutral-fg);color:var(--w7-neutral-fg);background:var(--w7-surface);border-radius:var(--w7-radius-control);font-size:var(--w7-fs-caption);cursor:pointer\">\\u8c41\\u514d\\u653e\\u884c</button>',",
  "              ].join(''))",
  "          : '<span style=\"color:var(--w7-text-weak)\">\\u2014</span>') + '</td>',",
  "        '</tr>'",
  "      ].join('');",
  "    }).join('');",
  "  root.innerHTML = [",
  "    state.note === '' ? '' : '<div style=\"padding:6px 10px;margin-bottom:6px;border-radius:var(--w7-radius-control);font-size:var(--w7-fs-body);background:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-bg)' : 'var(--w7-negative-bg)') + ';color:' + (state.note.indexOf('\\u2713') === 0 ? 'var(--w7-positive-fg)' : 'var(--w7-negative-fg)') + '\">' + esc(state.note) + '</div>',",
  "    '<div style=\"display:flex;gap:6px;align-items:center;margin-bottom:8px;flex-wrap:wrap\"><b>\\u4e09\\u5355\\u5339\\u914d\\u5dee\\u5f02\\u5de5\\u4f5c\\u53f0</b><span style=\"color:var(--w7-text-weak);font-size:var(--w7-fs-caption)\">\\uff08\\u4ed8\\u6b3e\\u524d\\u6821\\u9a8c\\uff1a\\u5df2\\u6536\\u8d27\\u91cf \\u2265 \\u8d26\\u5355\\u91cf\\u624d\\u653e\\u884c\\uff1b\\u5904\\u7f6e\\u72b6\\u6001\\u673a open \\u2192 resolved/waived\\uff09</span></div>',",
  "    '<div style=\"margin-bottom:8px\">' + chips + '</div>',",
  "    state.issues.length === 0",
  "      ? '<div style=\"color:var(--w7-positive-fg);font-size:var(--w7-fs-body)\">\\u5f53\\u524d\\u65e0\\u5dee\\u5f02\\u884c\\uff08\\u5168\\u90e8\\u53d1\\u7968\\u6536\\u8d27\\u00b7\\u4ef7\\u683c\\u52fe\\u7a3d\\u4e00\\u81f4\\uff09</div>'",
  "      : '<table style=\"border-collapse:collapse;width:100%\"><thead><tr style=\"background:var(--w7-surface-2);font-size:var(--w7-fs-caption);font-weight:600;color:var(--w7-text-secondary)\">',",
  "        '<th style=\"' + cell + ';text-align:left\">\\u53d1\\u7968 / PO</th><th style=\"' + cell + ';text-align:left\">\\u5dee\\u5f02\\u7c7b\\u578b</th><th style=\"' + cell + ';text-align:left\">\\u5bf9\\u62cd\\u660e\\u7ec6</th><th style=\"' + cell + ';text-align:left\">\\u72b6\\u6001</th><th style=\"' + cell + ';text-align:left\">\\u5904\\u7f6e</th></tr></thead><tbody>' + rows + '</tbody></table>'",
  "  ].join('');",
  "}",
  "window.__w6b9MatchWb = { state: state, refresh: load };",
  "setTimeout(() => {",
  "  const root = document.querySelector('[data-w6b9=\"match-wb\"]');",
  "  if (!root) return;",
  "  root.addEventListener('input', (ev) => {",
  "    const t = ev.target;",
  "    if (t && t.getAttribute && t.getAttribute('data-in') === 'resolve-note') state.resolveDraft = String(t.value || '');",
  "  });",
  "  root.addEventListener('click', (ev) => {",
  "    const f = ev.target.closest ? ev.target.closest('[data-filter]') : null;",
  "    if (f) { state.filter = String(f.getAttribute('data-filter') || ''); render(); return; }",
  "    const b = ev.target.closest ? ev.target.closest('[data-act=\"resolve\"],[data-act=\"resolve-confirm\"],[data-act=\"resolve-cancel\"]') : null;",
  "    if (!b) return;",
  "    const whatAct = String(b.getAttribute('data-act'));",
  "    if (whatAct === 'resolve') {",
  "      state.resolveSel = Number(b.getAttribute('data-id'));",
  "      state.resolveKind = String(b.getAttribute('data-kind')) === 'waived' ? 'waived' : 'resolved';",
  "      state.resolveDraft = state.resolveKind === 'waived' ? '\\u8c41\\u514d\\u653e\\u884c\\uff08\\u4ef7\\u683c\\u5dee\\u5f02\\u5df2\\u786e\\u8ba4\\uff09' : '\\u5904\\u7f6e\\u5b8c\\u6bd5\\uff08\\u8865\\u6536/\\u51b2\\u5e73\\u5df2\\u843d\\u5b9e\\uff09';",
  "      render();",
  "      return;",
  "    }",
  "    if (whatAct === 'resolve-cancel') {",
  "      state.resolveSel = 0; state.resolveKind = ''; state.resolveDraft = '';",
  "      render();",
  "      return;",
  "    }",
  "    if (state.inFlight) return;",
  "    const kind = String(b.getAttribute('data-kind')) === 'waived' ? 'waived' : 'resolved';",
  "    const noteEl = root.querySelector('[data-in=\"resolve-note\"]');",
  "    const note = noteEl ? String(noteEl.value || '').trim() : '';",
  "    if (note === '') { state.note = '\\u2718 \\u5904\\u7f6e\\u8bf4\\u660e\\u4e0d\\u80fd\\u4e3a\\u7a7a\\uff08\\u7559\\u75d5\\u662f\\u5904\\u7f6e\\u7684\\u5ba1\\u8ba1\\u9762\\uff09'; render(); return; }",
  "    state.inFlight = true;",
  "    void api('/fin/match/resolve', { issue_id: Number(b.getAttribute('data-id')), action: kind, note: note }).then(async (out) => {",
  "      const verdict = out.json && out.json.ok",
  "        ? '\\u2713 \\u5904\\u7f6e\\u6210\\u529f\\uff08' + (kind === 'waived' ? '\\u8c41\\u514d\\u653e\\u884c' : '\\u5904\\u7f6e\\u5b8c\\u6bd5') + '\\uff09\\uff1a' + note",
  "        : '\\u2718 \\u5904\\u7f6e\\u88ab\\u62d2\\uff08HTTP ' + String(out.status) + '\\uff1a' + String((out.json && (out.json.message || out.json.error)) || '') + '\\uff09';",
  "      state.resolveSel = 0; state.resolveKind = ''; state.resolveDraft = '';",
  "      await load();",
  "      state.note = verdict;",
  "      state.inFlight = false;",
  "      render();",
  "    });",
  "  });",
  "  void load();",
  "}, 0);",
].join('\n')
